plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Ladysnake"
        url = "https://maven.ladysnake.org/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    implementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

    include "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "aetherworld_litrpg" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def javaVersion = 25

tasks.withType(JavaCompile).configureEach {
    options.release = javaVersion
    options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
    withSourcesJar()
}

jar {
    archiveBaseName = project.archives_base_name
    archiveVersion = project.version
}
